loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[31mWARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[ WARN:0@0.736] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/deep/DATA/data/anti-vibration_hammer/640/train2017/DJI_0358.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "train_net.py", line 69, in <module>
    main()
  File "train_net.py", line 66, in main
    train(network, cfg)
  File "train_net.py", line 50, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/deep/1-POJECT/e2ec/e2ec/train/trainer/trainer.py", line 30, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/deep/1-POJECT/e2ec/e2ec/dataset/train/base.py", line 94, in __getitem__
    width, height = img.shape[1], img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'